### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by yuchi** [michael/hub#40]
At this moment I cannot fully reproduce the flow of a pubblication (for example) and I cannot guarantee to @vectorsize that APIs are working right (related to #38).

For this reason I'm going to create tests. I need @michael to implement the flow tests, btw.

Probably I'll use [visionmedia's supertest](https://github.com/visionmedia/supertest)

**Comment by yuchi** [comment]
Do you guys have some preference for a specific TDD framework? Personally I'd stick to mocha.

**Comment by yuchi** [comment]
Basic tests implemented.

**Comment by vectorsize** [comment]
So I've managed to run the tests in the local hub, here's what I guet:  
![](http://f.cl.ly/items/0H1s033c3C302i172w3C/Screen%20Shot%202013-02-11%20at%206.29.14%20PM.png)

Now, does this mean that everything should work as expected?
I'm obviously now running on the latest hub on the master branch and when trying to publish a document with both  the latest master-branch Composer and the latest production-branch Composer I don't get any server response error anymore in the console, probably due to your latest changes.  
Should I wait for an updated Composer version?
